### PR TITLE
Sets first letter of all sirupsen imports lower-case

### PR DESCRIPTION
**Pull request by stweiz**
This pull request sets all import paths and other references of "sirupsen" to lower case letters, so everything should be unified.

### CODE REVIEW

**Comment by sirupsen** [comment]
This is going to break Logrus from too many people yet. We'll have to create a new syslog package, preferably out of repo, that imports lower-case.

**Comment by schultz9999** [comment]
We have a patch to go thru sources and do the manual patch once we import to vendor dir :-/

**Comment by schultz9999** [comment]
If it's a breaking change, why not to release a major version?

**Comment by sirupsen** [comment]
This was done in master with a bump of a major version.

**Pull request closed without merging**
