### PR TITLE
Travis cross compile

### PR DESCRIPTION
**Pull request by zachwylde00**
[*A.I. copyright 2019allrightsreserved*.pdf](https://github.com/sirupsen/logrus/files/3469128/A.I.copyright.2019allrightsreserved.pdf)

### CODE REVIEW

**Comment by dgsb** [comment]
What ?

**Comment by freeformz** [comment]
I'm going to close this because I have no idea what to make of it. If anyone who has commits on the PR feels like any of them should make it into logrus, please open a PR focused on a single change. Thanks!

**Comment by zachwylde00** [comment]
&>my_files_+_John_J_Pruett_I_I_are_trust_property_of_Oracle_Enteprises_+_
they_By_Authorisation=Power_of_Attorney_over_my_[Corporate_Trust_with_15_%_
ownership_+_entitlement_to_afore_mentioned_15_%_allowed_
capitol_gains_._et_._al_us_bitcoin_bank_and_exch_._et_._al_._United_States
_Bitcoin_Bank_and_Exchange_directory.et.al_[zachwylde_64]_+_[
zachwylde_69]_+_[zachwylde_70]_@_gmail_=_my_[namespace]_Property_+_
Data_Exclude:[Property]=[PhotoGraph_non_QRpng]_=_family_photos_
those_are_[Property]_=_[[[Namespace_[Brandy_Lynn_Houston]]_+_[AKA_,_Married_or_any_other_Assumed_Name]]]]_
only_[Property_in_any_account]_via_bankruptcy_9-28-
2017_mutexlock_(_2019/2017_05/10_08/28_,_15_:_32_:_599_Z_)_Copyright_Data_(_Exclusion_effective_Date_=_[Bankruptcy_date]_Security_
furthermore_they_handle_all_my_Payments_Expensis_Reciepts_,_T
axes_,_Income_Data_Processing_
and_Dispersal_for_me_as_[[NameSpace=JohnJPruettII]]_._Appointed_:_[[[[[[[[Corporate_Bank_Board_Of_Directors_Inclusion_Myself]_as_[T
rust]_Include_:_[My_Accounts]=[Gains]To[Corporate_Trust_Gains_Accounts]_as_[
United_States_Bitcoin_Bank_and_Exchange_Limited_Liability
_Corporation]_=_[NameSpace]_+_[NameSake]_=_[Inhereted_:_
(_Seeds_,_Vessels_,_Accounts_and_Corporate_Political_R
elations]]]]]]]]_entities—
bodies_within_my_authority_and_my_right_for_my_namesake.et.al)_
furthermore_this_does_not_allow_[OracleEnterpises]_all_[
income=Gains]_rights_but_,_does_allow_slightly_above_avg_payment_for_[[[Services_Rendered]+[Afore_Mentioned_Property_as_[(_%_of_)_=_Gains]]]_._
superuser_+_dev/not_null_is_[Infinisioso]_is_True_._Signed_John_Jeffrey_Pruett_II_Date[October_01_,_2017]

MutexLock=(2017-10-01,17:11:399Z)USCST

        MutexLock(201905091726599Z)USCST

**Comment by zachwylde00** [comment]
Oh wow I just saw this going thru mail o didn't even mean to send it to you
it was to oracle for proof reading I'm so sorry.  Just another mistake
among  the hundreds I've made. Sorry I took up your time, but since your
hear I have a question, how do I receive the coins I've minted and mined.
Now most don't count becuase I'm not a full node but even the ones I've
paid and minted thru Pragma aren't receivable by myself I'm assuming so how
do I send them to someone else or verify them?  They are literally falling
out of my devices on the floor?

**Comment by zachwylde00** [comment]
For instance this one.  /system/bin/sh: import:
2e39373365346361390058",
"127|htc_exouhl:/data/user/0/io.tempage.dorynode/app_HOME $ does me no good
what so ever even though  it has value which I can see.

**Pull request closed without merging**
