### PR TITLE
Fixed issue #599

### PR DESCRIPTION
**Pull request by michaelvlaar**
Fixed issue #599

### CODE REVIEW

**Comment by dmathieu** [comment]
If this does work, why do we keep the multi-os terminal files? Couldn't we now have a single one?

**Comment by michaelvlaar** [comment]
I've only tested this on windows. For windows this works, it looks like it may also work on the other platforms. I'm not able to test on linux for now.. I would like a single function as well.

**Comment by dmathieu** [comment]
Provided it works, we could actually even entirely retire that method.

**Comment by samuelakerman** [comment]
Hello. Was this issue fixed? I am still getting:
terminal_windows.go:78: undefined: windows.Syscall

**Comment by dmathieu** [comment]
This isn't merged. Also, there's another PR resolving it on #604.
Feel free to try it and confirm it works on your OS.

**Comment by AnotherGoogleFan** [comment]
I tried go get -u -v just now and find it still cannot be build. 
```terminal_windows.go:78: undefined: windows.Syscall```
still this error.

**Pull request closed without merging**
