### PR TITLE
Add mail hook

### PR DESCRIPTION
**Pull request by zbindenren**

### CODE REVIEW

**Comment by Sirupsen** [comment]
Why was it closed?

**Comment by zbindenren** [comment]
Mainly because I thouht you are not interested in that hook.

**Comment by Sirupsen** [comment]
I'm interested, just haven't gone around to reviewing it.

**Comment by Sirupsen** [comment]
For this to become an official hook it needs more tests.

**Comment by Sirupsen** [comment]
Hey, I'm trying to move formatters and hooks out of core. Do you mind moving this under your own name + add tests, and squash this PR into adding it to the table in the README?

**Comment by rifflock** [comment]
@zbindenren do you think you might host on your github? The code looks solid and I'd like to use it in my logrus implementation.

**Comment by zbindenren** [comment]
Yes I can, I'll do it when I am back from vacation (in 2 days)

**Comment by zbindenren** [comment]
it is available now: github.com/zbindenren/logrus_mail

**Comment by zbindenren** [comment]
Closing

**Pull request closed without merging**
