### PR TITLE
Possible fix for issue #137

### PR DESCRIPTION
**Pull request by rsterbin**
If you pass an error to json.Marshal, you lose the message.  Here's one way the message might get added back in.

### CODE REVIEW

**Comment by Sirupsen** [comment]
What's the root of this "bug"? There's nothing in `logrus` that would remove this message as far as I can see, in fact, the Airbrake hook actively uses this field. I haven't tried to reproduce this on my own yet.

`prefixFieldClashes` is what deals with this type of error, but I'm hesitant to merge in this fix without understanding the root cause.

**Comment by rsterbin** [comment]
The root of the bug is how json.Marshal handles errors:

{code}
package main

import (
    "encoding/json"
    "errors"
    "fmt"
)

func main() {
    data := make(map[string]interface{}, 1)
    data["error"] = errors.New("Here is an error message")
    serialized, _ := json.Marshal(data)
    fmt.Println(string(serialized))
}
{code}

Produces:

{code}
{"error":{}}
{code}

**Comment by Sirupsen** [comment]
In that case don't we just need to cast the errors to strings before marshalling, rather than prefixing the fields?

**Comment by rsterbin** [comment]
We could, but it would mean that custom errors might lose information.  For example:

```
package main

import (
    "encoding/json"
    "fmt"
)

type CustomError struct {
    Message string `json:"message"`
    Count   int    `json:"count"`
}

func (e *CustomError) Error() string {
    return fmt.Sprintf("%d - %s", e.Count, e.Message)
}

func main() {
    data := make(map[string]interface{}, 1)
    data["error"] = &CustomError{"Here is an error message", 2}
    if err, ok := data["error"].(error); ok {
        data["error.msg"] = err.Error()
    }
    serialized, _ := json.Marshal(data)
    fmt.Println(string(serialized))
}
```

Produces:

```
{"error":{"message":"Here is an error message","count":2},"error.msg":"2 - Here is an error message"}
```

**Comment by aybabtme** [comment]
I'd prefer not changing the key of the key-value.

**Comment by Sirupsen** [comment]
Fixed in https://github.com/Sirupsen/logrus/commit/8287db79348cd82752b91ee2b7dd5fd274982c65

**Pull request closed without merging**
