### PR TITLE
LogstashFormatter - implement support for Host field

### PR DESCRIPTION
**Pull request by ovr**
Hey!

This will be rly cool to setup @host once on Struct creating
What do you think about this?

Thank 🍰

### CODE REVIEW

**Comment by dedpikhto** [comment]
👍

**Comment by ovr** [comment]
ping @Sirupsen 
Hey! Can you review it? And say is it okey?

Thanks

**Comment by ovr** [comment]
ping @Sirupsen

**Comment by sirupsen** [comment]
This formatter has been moved out of core

**Pull request closed without merging**
