### PR TITLE
MOD: add setOutput for the logger

### PR DESCRIPTION
**Pull request by git-hulk**
Add SetOuput function for the logger, related issue: https://github.com/sirupsen/logrus/issues/501

### CODE REVIEW

**Comment by git-hulk** [comment]
@sirupsen can you review this pull request? Or any suggestions?

**Comment by driskell** [comment]
Yes would absolutely love to see this added. At the moment this makes Logrus not a direct replacement for the stdlib log, which does have this functionality.

:+1:

**Comment by git-hulk** [comment]
@driskell Fixed, thanks for your review.

**Comment by driskell** [comment]
Hi @dmathieu - Do you know if there's anything that would stop this being merged? Would be great to see it added so there is additional API compatibility with stdlib. Also thanks for your hard work on logrus - I'm looking forward to using it :+1: 😃

**Comment by dgsb** [comment]
This method is available since commit 0c03a05a and pr #682

**Pull request closed without merging**
