### PR TITLE
allow color customization and level text length customization

### PR DESCRIPTION
**Pull request by theAmneziac**
Adds 2 fields (```LevelColors``` and ```LevelTextLength```) to ```TextFormatter```, allowing the color and length of the level text to be customized.  Added color constants and made them uppercase/exported so that they can be used in defining custom colors.

### CODE REVIEW

**Comment by msiebeneicher** [comment]
funny - i created nearly the same PR before 5 days ;)
see https://github.com/sirupsen/logrus/pull/565/files

+1 for the feature

**Comment by theAmneziac** [comment]
@msiebeneicher whoops, I didn't notice that you had.  Your solution looks great, either way I'm happy if the feature can be added.

**Comment by msiebeneicher** [comment]
no worries^^ @sirupsen need to decide which PR he would like to merge ;)

**Comment by dmathieu** [comment]
Hey,

I am going to close this PR because the other one was opened first.
The idea really seems interesting though. Let's keep the discussion going there (I won't merge/comment there right now though, but I'll come back to it soon).

**Pull request closed without merging**
