### PR TITLE
Fix race condition in hooks that modify entry.Data by guarding access

### PR DESCRIPTION
**Pull request by iancmcc**
Fixes Sirupsen/logrus#364
I'm not sold on the aesthetics of the implementation, but it's the only way I can think of doing it without breaking existing hooks.

### CODE REVIEW

**Comment by iancmcc** [comment]
We can't guarantee hooks won't deadlock, unfortunately, so I've changed it to include a func called `entry.SetField(k , v)` that sets values in a protected way, for use in hooks.

**Comment by DsXack** [comment]
👍

**Comment by stevvooe** [comment]
Wouldn't it be better to treat `Entry.Data` as immutable. If a hook wants to change a value, it should copy the whole map and add an entry. It will be a lot safer in practice and basic operations won't be encumbered by locks.

**Comment by DmitriyMV** [comment]
Relevant #529

**Comment by danielzheng** [comment]
same issue in v1.3.0, panic: 
fatal error: concurrent map iteration and map write
github.com/sirupsen/logrus/entry.go:108

**Comment by dgsb** [comment]
@danielzheng can you provide any hints on how to reproduce thie error ?
This PR is quite old and some mutex protection has been added since in the master branch, I wonder if this PR would still fix the issues you've found.

**Comment by danielzheng** [comment]
> @danielzheng can you provide any hints on how to reproduce your error ?
> This PR is quite old and some mutex protection has been added since in the master branch, I wonder if this PR would still fix the issues you've found.

We found it's a bug in middleware, it's OK now.

**Comment by freeformz** [comment]
There are many conflicts and it's very old so I'm going to close this.

But, if this is something that still needs to be pursued, please resolve the conflicts and re-open the PR. Thanks!

**Pull request closed without merging**
