### PR TITLE
formatter.go: simplify prefixFieldClashes(Fields)

### PR DESCRIPTION
**Pull request by dolmen**
Minor refactoring: simplify the implementation of `prefixFieldClashes(Fields)` in formatter.go

### CODE REVIEW

**Comment by noxiouz** [comment]
It disallows optimization for ```_, ok```. So if the fields does not collade very often, the code becomes slower.

**Comment by dolmen** [comment]
Interesting. Do you have some links about those optimisations?

**Comment by noxiouz** [comment]
Look at this bench:
http://play.golang.org/p/O5lKruoQmY

Results on my laptop:
```
PASS
BenchmarkKandOK-4         	100000000	        11.2 ns/op
BenchmarkOkOnly-4         	300000000	         4.97 ns/op
BenchmarkKandOKNotExists-4	100000000	        16.4 ns/op
BenchmarkOkOnlyNotExists-4	100000000	        11.7 ns/op
ok  	github.com/mapbench	6.012s
```
You can look at asm code, which is generated in both cases with:
```
 go tool compile -S m_test.go
```

**Comment by aybabtme** [comment]
I think this reads better, and the performance difference due to compiler optimization doesn't bother me a lot. Especially, compiler optimizations like this are very hit-and-miss and I expect the SSA backend to improve things a lot.

**Pull request merged**
