### PR TITLE
Fix data race issue in TextFormatter. Fix for https://github.com/Siru…

### PR DESCRIPTION
**Pull request by pengzhai**
…psen/logrus/issues/217.

Fix for the issue we just reported in https://github.com/Sirupsen/logrus/issues/217

### CODE REVIEW

**Comment by pengzhai** [comment]
We have verified this fix on our internal CI system.

**Comment by noxiouz** [comment]
@pengzhai printColored uses timestamp format too. The signature should be changed to pass timestampFormat, otherwise it will use an empty f.timestampFormat

**Comment by pengzhai** [comment]
Good catch, @noxiouz! Fixed.

**Comment by pengzhai** [comment]
Any additional comment, anyone?

**Comment by Sirupsen** [comment]
sorry been on vacation

**Pull request merged**
