### PR TITLE
Fixed import

### PR DESCRIPTION
**Pull request by darrenmcc**

### CODE REVIEW

**Comment by jprobinson** [comment]
:bump:

Any chance this can get merged? This bug causes a compile time error for any app engine user.

**Comment by xrstf** [comment]
The same change needs to happen in ``terminal_solaris.go``.

**Comment by zeekay** [comment]
@sirupsen anything in particular holding up this PR? Logrus is breaking our build (and while we can manually apply this patch, it's annoying to deal with from the perspective of continuous integration).

**Comment by xrstf** [comment]
Our build includes running ``goimports``, which "accidentally" also fixes files in ``vendor/`` and hence these missing imports. Maybe this would help you as well?

**Comment by darrenmcc** [comment]
We've pinned to a previous working version with glide, but a _real_ fix is preferred.

**Comment by jprobinson** [comment]
Almost two weeks and no word from any maintainers on this extremely simple fix? This is pretty absurd especially given that these are compile time errors that should have never made It to master.

@sirupsen please pull this in. I don't want to remove logrus from gizmo, but this is pretty bad practice of OSS and I don't want my other engineers to deal with this kind of behavior on the future.

**Comment by sirupsen** [comment]
> Almost two weeks and no word from any maintainers on this extremely simple fix?

Would you like to help maintain Logrus? I'd be happy to make you a collaborator.

**Comment by sirupsen** [comment]
Fixed in v0.11.3

**Pull request merged**
