### PR TITLE
add hook for logentries

### PR DESCRIPTION
**Pull request by crunchywelch**

### CODE REVIEW

**Comment by aybabtme** [comment]
@crunchywelch can you rebase, a fix to the tests was pushed and should make your PR green

**Comment by crunchywelch** [comment]
@aybabtme ok, hopefully that does it!

**Comment by Sirupsen** [comment]
Hey, we're trying to move hooks and formatters out of core and be maintained by the people who actually use it. Do you mind creating a repository under your own name and squash this into a commit adding an entry to the table in the README?

**Comment by crunchywelch** [comment]
Yup! Will do it when I get a free moment, thanks!

On Thu, Apr 30, 2015 at 2:59 AM, Simon Eskildsen <notifications@github.com>
wrote:

> Hey, we're trying to move hooks and formatters out of core and be
> maintained by the people who actually use it. Do you mind creating a
> repository under your own name and squash this into a commit adding an
> entry to the table in the README?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sirupsen/logrus/pull/169#issuecomment-97682744>.
>



-- 

Aaron Welch
SVP of Product
---
212.933.9785 x301
welch@packet.net

**Pull request closed without merging**
