### PR TITLE
Fix bug with quoting only strings and errors.

### PR DESCRIPTION
**Pull request by PurpureGecko**
PR for issue #301

### CODE REVIEW

**Comment by aarongreenlee** [comment]
@PurpureGecko Thanks for contributing a pull request to improve the way logrus applies quotes. Can you please also contribute a test case? Thank you!!

**Comment by PurpureGecko** [comment]
Add some tests.

**Comment by alindeman** [comment]
Any news on this one @PurpureGecko @aarongreenlee ?

**Comment by PurpureGecko** [comment]
@aarongreenlee Do you have another remarks?

**Comment by dmathieu** [comment]
There's been an attempt merged in #575 recently that tried fixing this.
Unfortunately, it didn't change anything. I just opened #580 to remove the `QuoteCharacter` option and be able to use `%q`, which should solve this safe encoding issue.

**Pull request closed without merging**
