### PR TITLE
Added TRACE level logging.

### PR DESCRIPTION
**Pull request by loren-osborn**
This is just a rebased update to PR https://github.com/sirupsen/logrus/pull/652

Please see discussion and history there.

### CODE REVIEW

**Comment by loren-osborn** [comment]
Added tests from #643 as @stevvooe suggested in #652.

**Comment by loren-osborn** [comment]
Pulled in a few improvements from #810.

**Comment by loren-osborn** [comment]
@stevvooe, I saw your comment: https://github.com/containerd/containerd/issues/2028

> @Random-Liu I am a maintainer there...
> 
> I think the problem with sirupsen/logrus#652 is that it is not backwards compatible for those using the interface to define a logger type. I'll LGTM it and see if that is a concern.

I understand your concern, but it rather makes me think we're using interfaces wrong. I think they should generally require the minimum functionality to accomplish what's required. All the logLevel methods are really convenience functions. Let me think on this a bit, but I think we can get a lot less repetitive code while making user-defined loggers much simpler and more adaptable.

The way `StdLogger` and `FieldLogger` are defined, they only make sense as a way to abstract logrus internal types. We could make implementing user-defined loggers dead simple, by adding a few interfaces and a bit of plumbing.

**Comment by loren-osborn** [comment]
@stevvooe I have some good ideas regarding interfaces for **useful** user-defined logging, but I think I will wait on implementation until this PR is merged in, so I don't have to make some of the changes twice.

@sirupsen, let me know if there are any additional blockers on reviewing and merging this PR, as it appears to have been kicking around in various forms for 2+ years now.

**Comment by gonix** [comment]
Looks good to me.

**Comment by Xiol** [comment]
Looks good to me too. Can't tell you how excited I am for this - can finally get rid of my trace level wrappers.

**Comment by dgsb** [comment]
@loren-osborn thank you for your contritbution, this looks mostly good to me, I've just requested a slight change in a test function.
We may also want to warn all hooks implementers of this new level before tagging this new version.
Even if it is a non-breaking api change it may have impact on how the hooks are implemented.

**Comment by loren-osborn** [comment]
@dgsb, Thanks for the quick feedback. I know everybody is eager to have this in a new release, but I have one more change in mind (that I mentioned above in my comment to @stevvooe ) after this is merged that would further extend `Ext1FieldLogger`, and I'd prefer not to add an **additional** `Ext2FieldLogger` for these new methods, so perhaps you could hold off on a release a few days until my next PR is ready?

**Comment by dgsb** [comment]
@loren-osborn, there is indeed no need to tag immediately a new version. I usually tag a new version at the beginning of the month.

**Comment by loren-osborn** [comment]
@dgsb, I expect to make that a separate PR, so feel free to merge this whenever convenient.

**Comment by loren-osborn** [comment]
I should probably amend the last commit message to **PullRequest#844: Added Trace to TestLogLevelEnabled() (req’d by @dgsb)** before you merge this branch, but I won’t be at a computer for another 3 hours.

I can do it then, or you’re welcome to amend the commit before then if you have time.

Thanks.

**Comment by Dieterbe** [comment]
awesome. thank you so much. i've been wanting a trace level and now i have it :D :balloon:

**Comment by loren-osborn** [comment]
@dgsb, Given all the legwork you're needing to do here, It's likely a good idea to add a way for a hook implementor to query the range of the log levels, so if it changes again, the hook developers don't need to make additional chanes?

**Comment by dgsb** [comment]
@loren-osborn we don't need an api for that, we already have the variable AllLevels which gathers all existing levels.
Anyhow, hooks implementors needs to be warned when we add a new level, especially ones with a high volume.

**Comment by loren-osborn** [comment]
Something like `AllLevels` is exactly what I had in mind. I’m sorry I hadn’t noticed it there before.

**Pull request merged**
