### PR TITLE
optimise: break when logger.out is dev/null

### PR DESCRIPTION
**Pull request by plusplus1**

### CODE REVIEW

**Comment by stevvooe** [comment]
While this is a good optimization for `ioutil.Discard` or a `nil` output, it won't handle cases where `/dev/null` is opened separately.

If that is sufficient, LGTM.

**Comment by alexlry** [comment]
Test for Logger.Out could be made on line 100 instead of line 127. This would also prevent using bufferPool when Logger.Out is disabled.
https://github.com/keymantics/logrus/commit/5e2f1ff435f036aa7e1c5b088d1b0938bc6fd279

**Comment by dgsb** [comment]
hello @plusplus1, thanks for your contribution. But I'm not sure the added complexity worth it. The use case seems narrow to me.

**Comment by dgsb** [comment]
No feedback from initial commiter. The use case is rather narrow and the added value vs the added complexity does not seem to being worth it.

**Pull request closed without merging**
