### PR TITLE
default logs to stderr

### PR DESCRIPTION
**Pull request by aybabtme**
This makes me rage always, I think it's worth fixing.
@Sirupsen 

Pretty good rationale on when to use stdout/stderr by @jstorimer:
http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

### CODE REVIEW

**Comment by Sirupsen** [comment]
I definitely agree with this, and it's been brought up multiple times. I'm unsure whether or not to ship this before or after 1.0

**Comment by aybabtme** [comment]
I've bumped the version to `0.8` for that purpose. Any reason why you would prefer making the change in `1.0`?

**Comment by Sirupsen** [comment]
@stevvooe @icecrime would this have any heartbreaking implications for Docker?

**Comment by stevvooe** [comment]
@Sirupsen For the registry (docker/distribution), this would change the output location of the logs. This may affect infrastructure consuming those log messages if they don't also consume `stderr`. I don't see an issue with this. Logs should go to `stderr`.

**Pull request merged**
