### PR TITLE
Add Seq to list of hooks

### PR DESCRIPTION
**Pull request by nullseed**

### CODE REVIEW

**Comment by nullseed** [comment]
Bump

**Comment by nullseed** [comment]
Bump, is there anything holding back this being merged?

**Comment by dgsb** [comment]
We have recently removed the list of hook from the readme and added them in [this](https://github.com/sirupsen/logrus/wiki/Hooks) wiki page in order to avoid needing a pr for each newly documented hook.
@nullseed  Can you update the wiki page with this hook ?

**Comment by nullseed** [comment]
Done 👍

**Pull request closed without merging**
