### PR TITLE
Make Fields an implementable interface with a ToFields() method, issue

### PR DESCRIPTION
**Pull request by alecha**
Following the discussion started for issue #207, I’ve created a simple way to have the Fields type as implementable interface with a ToFields method.

### CODE REVIEW

**Comment by Sirupsen** [comment]
Is `ToFields()` really the best name? This makes a ton of sense in the context of Logrus, but may not for someone reading code who're not familiar with Logrus. I don't have a great idea.

An alternative to this approach showed up her: https://github.com/Sirupsen/logrus/pull/249 What do you think about this?

Tests and documentation would be needed when this proposal would be ready to be accepted.

@aybabtme

**Comment by aybabtme** [comment]
I think this would work better if we had a call that takes varargs, alike to the way `go-kit/log` does it:

```go
log.With(keyvals ...interface{})

// log.With("key","val", "other_key", "other_val").Info("hello")
```
problem with ^ is that proper usage of the logger isn't a compile-time check:
````
func (l *log) With(keyvals ...interface{}) log {
   if len(keyvals) % 2 != 0 {
      keyvals = append(keyvals, "<MISSING VALUE>")
   }
   for i := 0; i < len(keyvals); i+=2 {
      k := keyvals[i]
      v := keyvals[i+1]
      // do something with k,v
   }
}
```

The advantage of this, however, is that since you have `interface{}`, you can type-check to see if the value implements a `log.Valuer` interface:

```go
for _, kv := range keyvals {
   if valuer, ok := kv.(log.Valuer); ok {
      k := valuer.Key()
      v := valuer.Value()
      // do something with k,v
      // remove valuer from keyvals
   }
   // continue with k=kv[i], v=kv[i+1]
}
```

~but, since we don't do that, we can't really do a type-check like that. =P

* * *

So I think the idea is valuable, but I my take on this is that I wouldn't change the current API to take a different type of argument. While this would theoretically work with people using the logger as is, it wouldn't work for people who wrap logrus to make their own customized logger, which is a lot of people.

So hum, I'm not sure what the right course of action here is. Having a way to 'hint' that a type knows how to split in 'key-values' would be nice, but I don't think this is the right solution for now.

**Comment by alecha** [comment]
I can understand, actually I'd rather not add a new dependency (even if Golf is nice and widely used, so if the decision is to add a new dependency this may be the better choice) and I don't like so much the varargs solution because I tend not to use interface{} in my go programs, but it's probably not always possible ;)

Regarding the ToFields() name, because of is an interface declared in logrus, I think is reasonable if the name has a meaning who is related to logrus.

**Comment by noxiouz** [comment]
Will be any updates here?

**Comment by alecha** [comment]
I think that we can think about a better name instead using "ToFields()",  I don't know if @Sirupsen prefers to include the other PR which adds the Golf dependency.

**Comment by aybabtme** [comment]
Sorry for the long delay here. This will break existing users that may have aliased the `Fields` type to something else, without implementing the `ToFields` interface. Because this breaks backward compatibility, I'll close. 

I think it would be a good idea for a 1.0 rewrite, however, to make the Fields an interface. So I'll tag this as 1.0.

**Pull request closed without merging**
