### PR TITLE
add filepath and line

### PR DESCRIPTION
**Pull request by erlang-boy**

### CODE REVIEW

**Comment by lsgrep** [comment]
could you fix this imcompatibility problem @erlang-boy  , so that this PR could be reviewed thanks.

**Comment by businiaowyf** [comment]
This is an important feature, I also need it.

**Comment by businiaowyf** [comment]
However, you can't make the parameter of  Caller() as a fixed number 2, it's not fixed

**Comment by freeformz** [comment]
If this PR is still of interest, please resolve the conflicts.

Thanks!

**Comment by freeformz** [comment]
Thank you, but in order to clean up older PRs and issues (this PR is > 2 years old), I'm going to close this PR. Feel free to re-open with an updated branch if this is still of interest. PS: I'm sorry this sat for so long.

**Pull request closed without merging**
