### PR TITLE
fix race conditions on entry

### LINKED ISSUE #1046: Race condition in entry.Data on calling WithFields() method
```
fatal error: concurrent map iteration and map write
runtime.mapiternext(0xc000bbee98)
	/usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc000bbedd8 sp=0xc000bbed50 pc=0x1011289
vendor/github.com/sirupsen/logrus.(*Entry).WithFields(0xc0001065b0, 0xc0009d3f50, 0xc0009d3f50)
	vendor/github.com/sirupsen/logrus/entry.go:117 +0xef fp=0xc000bbef08 sp=0xc000bbedd8 pc=0x1479b0f```

### PR DESCRIPTION
**Pull request by lwsanty**
closes #1046

### CODE REVIEW

**Comment by blocknonip** [comment]
This is still a bug. It occurs with any use of Entry and a hook (i.e. logrustash).

**Comment by markphelps** [comment]
Thank you @blocknonip!!. Sorry for the stalebot spam. I thought it would only label/comment on issues, not PRs too.

**Comment by flimzy** [comment]
This lock is far too aggressive. It locks the entire logger, rather than a single entry as it should.

**Comment by dgsb** [comment]
Agree, we should find a better solution than this one.

**Comment by markphelps** [comment]
@flimzy my apologies for merging this so quickly. would you want to work on a PR to lock only the entry? If not I can early this coming week.

**Comment by flimzy** [comment]
I looked at it briefly before posting my comment, and it wasn't immediately obvious the proper solution.  It looks like we need to add a mutex to the `Entry` type, and lock it in `WithFields` and in `fireHooks`, but my first attempt lead to a deadlock.

It's possible that we have other overly-aggressive locks which could be relaxed, too, but it's tricky to do that with confidence, without tests covering all possible races (which are incredibly hard to test).

I'll try again if I have time, but you may get to it faster than me.

**Comment by markphelps** [comment]
@flimzy ok I created #1122 to track. I'll also try taking a look

**Pull request merged**
