### PR TITLE
Safely format data when printing

### LINKED ISSUE #531: Unsafe escaping of log data
I've noticed the output of a program appeared to be broken with logrus, this seems to be due to [appendValue][1].

```
	case string:
		if !f.needsQuoting(value) {
			b.WriteString(value)
		} else {
			fmt.Fprintf(b, "%s%v%s", f.QuoteCharacter, value, f.QuoteCharacter)
		}
```

It seems %v doesn't sufficiently escape the string, I think the else branch should be replaced with:
```
			fmt.Fprintf(b, "%q", value)
```

[1]: https://github.com/sirupsen/logrus/blob/67bca5dc4fe4e689c042885ca5b09e1df1356979/text_formatter.go#L171-L189

### PR DESCRIPTION
**Pull request by kpcyrd**
Fixes #531

### CODE REVIEW

**Comment by dmathieu** [comment]
To follow up on your comment in the other issue, it doesn't seem to me like that option has any actual use.
But it should then be entirely removed, not be kept around broken ☺️

**Comment by seiffert** [comment]
I agree with @dmathieu. The idea of having such an option is nice, however I also think that the use cases are limited. 
The option should either be removed from the library or be used. If you agree to use the option, `strconv` has a function `quoteWith` that basically does the same thing.

**Comment by kpcyrd** [comment]
I'd prefer if somebody else could take over this PR, I'm not actually a golang developer, I've just noticed logrus logs insecurely.

**Comment by seiffert** [comment]
Hey @kpcyrd, I'm happy to take this one over from you. I've copied your commit into #575 and will implement quoting with `QuoteCharacter` in there. (you can close this PR if you want)

**Comment by kpcyrd** [comment]
@seiffert thanks!

**Pull request closed without merging**
