### PR TITLE
*Level implements flag.Value

### PR DESCRIPTION
**Pull request by glasser**
This lets you do something like:

``` go
var logLevel logrus.Level = logrus.InfoLevel
func init() {
  flag.Var(&logLevel, "log-level", "logrus log level")
}
func main() {
  flag.Parse()
  logrus.SetLevel(logLevel)
}
```

### CODE REVIEW

**Comment by Sirupsen** [comment]
This has come up enough time I'll consider merging it into core, but it needs a better name than `Set`. `SetFromString` also doesn't quite chime right.

**Comment by glasser** [comment]
But Set is the name of the flag.Value interface method.  If you use a different name, then you can't use it with `flag.Var`.

**Comment by flyinprogrammer** [comment]
have we thought about using environment variables to set log levels?

**Comment by aybabtme** [comment]
I think this can be done outside of logrus, and accepting this would open the door to then accepting all kind of different ways to set the level. For those reasons, I'm not a fan of adding this. 

@Sirupsen: you're open to the idea, do we merge?

**Comment by aarongreenlee** [comment]
I do understand @glasser's reasoning; however, I agree with @aybabtme. It is my opinion that the main program is responsible for sourcing it's configuration and it is then responsible for instructing logrus using the logrus' exported API.

**Comment by dmathieu** [comment]
With ParseLevel being public, implementing this manually is entirely possible, and exposing ParseLevel allows for more extensibility.

Closing this as I'm trying to clear the issues and PRs.

**Pull request closed without merging**
